name: 部署到 Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 拉取 main 分支代码（为了拿到根目录的 index.html 和 CNAME）
      - name: Checkout repository
        uses: actions/checkout@v6

      # 2. 获取数据制品的 Run ID
      - name: Resolve latest run-ids of koi & astr
        id: runids
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          KOI_WF_ID=$(gh api "/repos/${{ github.repository }}/actions/workflows/koi.yml" --jq '.id')
          ASTR_WF_ID=$(gh api "/repos/${{ github.repository }}/actions/workflows/astr.yml" --jq '.id')

          KOI_RUN_ID=$(gh api "/repos/${{ github.repository }}/actions/workflows/$KOI_WF_ID/runs?per_page=1" --jq '.workflow_runs[0].id')
          ASTR_RUN_ID=$(gh api "/repos/${{ github.repository }}/actions/workflows/$ASTR_WF_ID/runs?per_page=1" --jq '.workflow_runs[0].id')

          echo "koi_run_id=$KOI_RUN_ID" >> "$GITHUB_OUTPUT"
          echo "astr_run_id=$ASTR_RUN_ID" >> "$GITHUB_OUTPUT"

      # 3. 下载动态数据
      - name: Download Koi Data
        uses: actions/download-artifact@v4
        with:
          name: koi-data
          path: dist/koi
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          run-id: ${{ steps.runids.outputs.koi_run_id }}

      - name: Download Astr Data
        uses: actions/download-artifact@v4
        with:
          name: astr-data
          path: dist/astr
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          run-id: ${{ steps.runids.outputs.astr_run_id }}

      # 4. 搬运静态文件到打包目录
      - name: Prepare static files
        run: |
          cp index.html dist/
          cp CNAME dist/
          touch dist/.nojekyll

      # 5. 部署（开启 force_orphan 确保每次都是干净的孤儿提交）
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          force_orphan: true
